[package]
name = 'ezfinance'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]

ezfinance="c6e04f2012b4a3a891a1f64628b6288e2d4bdd96dd3e233dce46491e4e517981"
